### ISSUE TITLE
STM32 Utility with USB-ST link v2 no connected

### ISSUE THREAD

**Issue by uhi2000** [NiklasFauth/hoverboard-firmware-hack#101]
Hello,
I have a problem with flashing the firmware with Windows 10. I have connected the USB -ST link v2 dongle as described without 3.3v.
The STM32 ST Utility 004 writes "Can not connect to target". I really do not use the 3.3volts? "why"???
please help.... I really not use the 3.3volts?
I have connected the motherboard with an external power supply 36V. a short answer would be nice....
best regards

**Comment by larsmm** [comment]
You have to hold the on-button during flashing. That powers the 3.3V. Press and hold button, flash, release button after flashing.

**Comment by uhi2000** [comment]
if I put the USB-Link dongle in the USB port of my PC, then I press the connected button in the STM32 Link Utility. but it always comes the error message "no target connected" of the stick but recognized in the STM32 link. What do I'm wrong ???
as long as there is no connection with the USB stick, I can not flash!!!please help me...

**Comment by uhi2000** [comment]
it may be, the mainboard is looked???

**Comment by uhi2000** [comment]
everything works now
