### ISSUE TITLE
[Solved] Wheels can't turn forward/Backward

### ISSUE THREAD

**Issue by Valentin2077** [NiklasFauth/hoverboard-firmware-hack#103]
Hello,

I have an issue concerning the hoverboard's wheels.
I tried using the following Inputs :

- 2 Potentiometers
- A Gametrak
- A Joystick

The motors can turn left or right, but can't move forward or backward
I am using the TranspOtter Branch.
I modified the programm so that i can control it with 2 potentiometers.
The motors have been calibrated by using a serial port of an arduino.

Any help would be appreciated

Kind Regards.

**Comment by uhi2000** [comment]
I have the same problem with the firmware-transpotter Ng-hack.mit the analog stick I can only control to the left and to the right. with the Nunchuk I have no function...

**Comment by larsmm** [comment]
Transpotter branch is for transpotter only. If you want analog joystick use master branch. The analog joystick code there is not working. I have working joystick code. But the driving behaviour is not nice and it needs some more testing. I have very little time at the moment. Maybe I will push it in a few weeks.

**Comment by p-h-a-i-l** [comment]
But it should therefore work with a Gametrak - that's the intended input for transpotter.

**Comment by Valentin2077** [comment]
Problem solved !

It was an error of cabling, and i modified the config.h file (Line 95).
The Gametrak works perfectly.

Thanks a lot for your help !

**Comment by uhi2000** [comment]
hi, a question: does your gametrak work in perfect in all 4 directions ???

**Comment by uhi2000** [comment]
hi lars ,
oder könntes du mir vielleicht mal deinen fertigen Hex-file mit config.h mit dem  Anschluss Gametrak rüber schicken?????

**Comment by Jan--Henrik** [comment]
Hi, you can find the latest (and only) release for the TranspOtter firmware here: https://github.com/NiklasFauth/hoverboard-firmware-hack/releases
and you can find detailed build instructions here:
https://github.com/NiklasFauth/hoverboard-firmware-hack/wiki/Build-Instruction:-TranspOtter
The release is tested and works perfectly fine.

Could you please stop hijacking threads? Thank you
