### ISSUE TITLE
Reverse is reversed in PPM mode

### ISSUE THREAD

**Issue by franck24300** [NiklasFauth/hoverboard-firmware-hack#114]
Hello
With Niklas firmware in PPM mode the direction when backing up is reversed.
That is to say if I put the joystick right when rolling forward the hoverboard goes right but if I put the joystick right in reverse the hoverboard goes to the left. Is there an option to change somewhere?

https://youtu.be/0yshyQtzFf4

**Comment by verial** [comment]
peut votre config.h et main.h ?

**Comment by verial** [comment]
can I have your config.h and main.h ?
