### ISSUE TITLE
Cant flash whitout 3.3v conected to stlink...

### ISSUE THREAD

**Issue by DaviVolcan** [NiklasFauth/hoverboard-firmware-hack#115]
When i try to flash the board using stlink v2 io, clk, gnd...i have no luck...(im following even the Power button instructions) Only when i plug the vcc from stlink to 3.3v on main board  I get conection and finally i can flash... Does someone knows why? 
the readme.md says that connecting vcc from stlink to 3.3 could kill the main board... Why? 

Thanks!

**Comment by Combinacijus** [comment]
I have heard that if you power stm32 microcontroller externally and also power from stlink you will burn it. Don't know if it's true but I don't wanna find out

**Comment by p-h-a-i-l** [comment]
@DaviVolcan Are you using an [original stlink/V2](https://www.st.com/resource/en/user_manual/dm00026748.pdf)? If I recall correctly, the need to be connected to 3.3V to sense the VCC voltage level.

**Comment by larsmm** [comment]
You do not want to have 2 3.3V sources: from stlink and from battery. If they are a bit different, current will flow where it is not very healthy.

If you power the mailboard from stlink only I do not now if the 3.3V regulator likes it to be powered from the wrong side.

**Comment by p-h-a-i-l** [comment]
see https://www.st.com/content/ccc/resource/technical/document/user_manual/65/e0/44/72/9e/34/41/8d/DM00026748.pdf/files/DM00026748.pdf/jcr:content/translations/en.DM00026748.pdf

![image](https://user-images.githubusercontent.com/10248772/61229043-b85a4e80-a727-11e9-9f6a-e9c157eb32c2.png)

**Comment by p-h-a-i-l** [comment]
You could also test my theory by keeping the board save. Either with a 100k resistor in series or an independent 3.3V source.

**Comment by alex-makarov** [comment]
I *probably* have the same issue as @DaviVolcan. ST-Link V2 clone connected to the correct pins, without 3.3V - as per instructions (I've checked that the connection is indeed correct, by testing directly on the pins of the MC). However neither st-link nor openocd can read anything, tried on two PCs.
 
The microcontroller (gd32f103 in my case) seems to be alive -- the board was new and functioning hoverboard; after disassembly it beeps two times on power-on and the onboard LED is blinking. I would want to try supplying the 3.3V but really don't want to kill the board - how exactly can I try it in safer way, @p-h-a-i-l ?

**Comment by DSBRobotics** [comment]
Measure the 3.3v on board and check ground.

**Comment by alex-makarov** [comment]
> Measure the 3.3v on board and check ground.

Ground OK, 3.3v looking good on the SWD programming header.

**Comment by alex-makarov** [comment]
Maybe any other ideas how to move further from the point of not being able to flash? What else to check? Thanks!

**Comment by alex-makarov** [comment]
OK, solved it! The problem was with ST-LINK firmware, apparently the programmer (cheap chinese clone of ST-Link v2) was shipped with some broken firmware. After I've updated it using ST Windows utility running in VirtualBox, everything worked.

**Comment by timsooonnnn** [comment]
this youtuber sells your hoverboard program for 1000. Isn't your program code free?
https://youtu.be/LOpbEYA0hio

**Comment by verial** [comment]
I'm flashing from St-link source.
