### ISSUE TITLE
PPM mode is mixing up channels

### ISSUE THREAD

**Issue by snowkingcro** [NiklasFauth/hoverboard-firmware-hack#116]
I flashed my hoverboard with PPM mode enabled! Whenever i pull the throttle i get different results.
1. - everything works great, throttle is smooth, back, forth, steering left& right.
2. - one wheel goes forward, other goes back.
3. - steering is reversed.

I used to measure the noise, it's quite low.
Cables are 5cm lenght.
Does someone know what is happenning?

**Comment by verial** [comment]
peut votre config.h et main.h ?

**Comment by verial** [comment]
can I have your config.h and main.h ?
