### ISSUE TITLE
Software differential(s) for four-wheel vehicles

### ISSUE THREAD

**Issue by gnbl** [NiklasFauth/hoverboard-firmware-hack#120]
I, too, am looking into converting a [bobby car](https://en.wikipedia.org/wiki/Bobby_Car) to electric drive, and reading up on drive train and suspension designs, I was wondering if and how a software differential (to accommodate the different wheel speeds) when making turns ("cornering") could be realized.

Otherwise, for rear drive, if both wheels simply have the same speed, the vehicle would be pushed straight ahead, reducing steering capabilities and causing slip on the front wheels, but also on the drive wheels once making a turn, since the inner wheel is rotating too fast while the outer wheel is  rotating too slow.
For front drive I assume it would not oppose the steering as much, but still cause slip.

I suppose a steering angle sensor (or gyro?) would be required for front or/and rear drive controllers to adjust wheel speeds respectively (depending on geometry).
These factors could be calculated at compile-time from defines of the vehicles geometry.

<hr/>
References

 - https://en.wikipedia.org/wiki/Self-balancing_scooter
 - https://en.wikipedia.org/wiki/Wheel_hub_motor
 - https://en.wikipedia.org/wiki/Drive_wheel
 - https://en.wikipedia.org/wiki/Differential_(mechanical_device)#Active_differentials
 - https://en.wikipedia.org/wiki/Torque_vectoring
 - https://en.wikipedia.org/wiki/Four-wheel_drive
 - https://en.wikipedia.org/wiki/Steering
 - https://en.wikipedia.org/wiki/Ackermann_steering_geometry

 - https://en.wikipedia.org/wiki/Car_suspension
 - https://en.wikipedia.org/wiki/Independent_suspension
 - https://en.wikipedia.org/wiki/Power_steering

**Comment by p-h-a-i-l** [comment]
Contrary to the variable name being "speed", the set point for motors is not a fixed speed. For that you'd need a closed loop control which is not implemented in this fork. 
The set point is the duty cycle for each motor. No differential needed.

**Comment by gnbl** [comment]
Thanks!
