### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by razvanavram** [NiklasFauth/hoverboard-firmware-hack#121]
Hello,

Can i use a raspberry pi to control the hoverboard movement (speed, acceleration and steering)?

If i am able to do it, how do i send commands to the board?
Do flash it using st-flash and then use the same pins to send the commands?
Did anyone use a raspberry pi to control it?

**Comment by verial** [comment]
https://github.com/isabellesimova/Hoverbot
