### ISSUE TITLE
Hall sensor as ADC throttle?

### ISSUE THREAD

**Issue by jtmnyy** [NiklasFauth/hoverboard-firmware-hack#126]
Hi guys,
im trying to use hall effect sensor throttle for ADC input, have it working well on 5v.
the only issue is the buggy will turn off when i completely release the throttle.
any ideas why this is happening?

**Comment by Untanux** [comment]
I always power up these hall effect sensors from 3.3V, because at least 49E sensor, at 5V power supply it will give about 4.1V output signals, witch is too much for ARM MCU on hoverboard.
