### ISSUE TITLE
Different Mainboard

### ISSUE THREAD

**Issue by Tiim12312** [NiklasFauth/hoverboard-firmware-hack#131]
Does anyone know the pinout for this type of mainboard? I cant seem to figure it out. Thanks!
![image](https://user-images.githubusercontent.com/29235291/70382772-5391d180-191e-11ea-87f5-90f0b613642e.png)

![image](https://user-images.githubusercontent.com/29235291/70382773-5c82a300-191e-11ea-8d6b-e190cfe2be49.png)

**Comment by Jan--Henrik** [comment]
No, sorry I have never seen such a main board :/
