### ISSUE TITLE
Gametrak docs

### ISSUE THREAD

**Issue by derjohn** [NiklasFauth/hoverboard-firmware-hack#133]
Hello,
could you please make a small documentation how the gametrak is supposed to work? In my case it's only rotating into one direction, it's now clear how to calibrate or use it to move left and right.

thx,
derjohn

**Comment by Candas1** [comment]
Hi,

Are you using the right branch?

**Comment by derjohn** [comment]
@Candas1 Probably not ... I see there is a transpotter branch , which lags about a year behind. I'll try that out!

**Comment by Jan--Henrik** [comment]
Hey, that sounds like rotation and length are mixed up
