### ISSUE TITLE
New version of motherboard

### ISSUE THREAD

**Issue by Ilyaprok** [NiklasFauth/hoverboard-firmware-hack#134]
Hello! I have a new version of motherboard. 
Is this firmware suitable for this board?
![image](https://user-images.githubusercontent.com/31244872/72438182-1db9f580-37c6-11ea-9a18-756f74394ed0.png)

**Comment by Jan--Henrik** [comment]
Please have a look at this thread: https://github.com/NiklasFauth/hoverboard-firmware-hack/issues/35

**Comment by Ruslanzz** [comment]
Мне попалась такая же плата, стандартные прошивки на ней не работают. Но она не сгорела при запуске и может дергать колесом.
