### ISSUE TITLE
For GD32F103 two main boards? 

### ISSUE THREAD

**Issue by abrarakram19** [NiklasFauth/hoverboard-firmware-hack#136]
Any firmware for GD32F103 two separate red main boards.? Is there a way to use both board separately for unicycle. With ADC potentios.

**Comment by Jan--Henrik** [comment]
Please have a look at this thread: https://github.com/NiklasFauth/hoverboard-firmware-hack/issues/35

**Comment by abrarakram19** [comment]
These threads are for GD32"F130" but i have GD32"F103"
