### ISSUE TITLE
How to hold position?

### ISSUE THREAD

**Issue by cohnhead66** [NiklasFauth/hoverboard-firmware-hack#137]
Is there a build that will hold position of wheels when speed set to 0? If not, any ideas on the best way to implement this?

I think i saw a build that could accept PID commands.  Can anyone help with this?

**Comment by Blimpyway** [comment]
This fork can be compiled with  speed control, which means the firmware struggles to maintain 0 rpm if that is requested. https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC

**Comment by cohnhead66** [comment]
Thanks,  Speed control works perfect for my application.
