### ISSUE TITLE
Flashing Problem ST-LINK

### ISSUE THREAD

**Issue by ACG-TR** [NiklasFauth/hoverboard-firmware-hack#139]
Hello I am new here, I try to flash the firmware i created from pioneerland to the new hoverboard mainboard i have.

I tried powering the mainboard from 36V battery, from the ST32 dongle(while disconnecting the battery) the red light is blinking when powered but i always get the same error as "cannot connect to target"

the cable connections are correct i checked 10 times already:) GND to GND CLK to CLK and DIO to DIO.

I was not able to unlock the unit as there is no clear tutorial about it. I am using windows 10. is it the problem?

Can anyone help please.

**Comment by larsmm** [comment]
I am using Windows 10 without any Problem. Update the firmware of your ST-Link v2 dongle using the newest version of ST-Link utility.

1. connect GND, CLK, DIO, connect USB
2. connect battery
3. press and hold power button of the mainboard
4. flash
5. release power button

**Comment by ACG-TR** [comment]
Already did those. St link utility does not see the board on the first page.

**Comment by larsmm** [comment]
Try to isolate the error: is it possible to flash another target?

**Comment by ACG-TR** [comment]
Hi, I tried your way, i bought bunch of mainboards. 2 of them, same result. But i suceeded in 1 older version. I think in the newer versions some kind of hardware protection is available. 

thanks.
