### ISSUE TITLE
[Feature request] Mirror motor speeds

### ISSUE THREAD

**Issue by Mr0Inka** [NiklasFauth/hoverboard-firmware-hack#14]
It was pretty easy to add a "* -1" to one of the motor speeds in the files, but would still be useful for some people to have a setting right in the config that makes both motors go in the same direction (for a scooter with both wheels mounted from the same side for example).

**Comment by LeoDJ** [comment]
Can you please clarify?  
If you want them to both be spinning in the same direction, you could use a `STEER_COEFFICIENT` of 1 and SPEED of 0, so basically, you are "turning", but both wheels should spin in the same direction. Then if you apply your throttle signal as "steering" input, then it is the same as flipping one motor direction.

If you want that as a config setting, then feel free to program it and create a pull request.
