### ISSUE TITLE
Are Schematics No Longer Available?

### ISSUE THREAD

**Issue by k3nden** [NiklasFauth/hoverboard-firmware-hack#147]
When I follow the link for the schematics it appears that the site has been abandoned. I am having a power issue and could really use a copy of the schematic....

**Comment by NopfatGithub** [comment]
https://wiki.warpzone.ms/_media/projekte:transpotter:20150722_hoverboard_sch.pdf

I hope this is a copy of the file you were looking for. Maybe somebody can confirm and safe it at archive.org

**Comment by k3nden** [comment]
@NopfatGithub Thanks!
