### ISSUE TITLE
Dont get the nunchuk control working

### ISSUE THREAD

**Issue by ctucx** [NiklasFauth/hoverboard-firmware-hack#16]
hello,
i dont get the nunchuk control working, i tried the the ADC control and that one is working.
i have tried both connectors, on two boards. nothing, and of cause i tried the nunchuk on an arduino: it works. i connected it to the board with 3k3 pullup on scl and sda...

Can someone help/ give tips?

**Comment by NiklasFauth** [comment]
How do you power the Nunchuck when connected to the mainboard?

**Comment by ctucx** [comment]
via the 3.3v rail.

**Comment by Manawyrm** [comment]
Hi ctucx,

that's probably EMI. You could try shielding the cable (if you can). A capacitor against ground might also help.
Are you using a real nunchuck? I had trouble with the cheap chinese nunchuck clones.

**Comment by ctucx** [comment]
yes, its a china clone. then i will buy a wireless nunchuck...

**Comment by Mr0Inka** [comment]
For me the China nunchuk was super buggy. Imitating it with an Arduino worked without any problem and went super smooth tho.

**Comment by rene-dev** [comment]
@NiklasFauth said they are missing bypass caps, adding 100n to the nunchuck fixed some issues.
