### ISSUE TITLE
Wrong comment about IRQ frequency

### ISSUE THREAD

**Issue by rene-dev** [NiklasFauth/hoverboard-firmware-hack#17]
this comment by @TomTinkering is wrong:
https://github.com/NiklasFauth/hoverboard-firmware-hack/blob/057407ae248c5eafa0e200938103e7880ab86253/Src/bldc.c#L146-L148
the irq is executed at 16 kHz, not 100. The ADC is synced to the timer trigger out:
https://github.com/NiklasFauth/hoverboard-firmware-hack/blob/057407ae248c5eafa0e200938103e7880ab86253/Src/setup.c#L461
and trigger out is fired on timer update:
https://github.com/NiklasFauth/hoverboard-firmware-hack/blob/057407ae248c5eafa0e200938103e7880ab86253/Src/setup.c#L401
all explained here:
https://github.com/NiklasFauth/hoverboard-firmware-hack/blob/057407ae248c5eafa0e200938103e7880ab86253/Src/setup.c#L23-L26

The ADC has to be synced to the pwm, and sample while the low fets are on, otherwise you cant measure the current, and all your other measurements will be noisy.

**Comment by TomTinkering** [comment]
Thanks, can't believe I missed that.
