### ISSUE TITLE
Hardware for the little custom board to link two mainboards

### ISSUE THREAD

**Issue by LayerDE** [NiklasFauth/hoverboard-firmware-hack#23]
Hi
Could you please tell me the specs and the name of the 3.3V stepdown you used of the board you use to conntect the nunchuck

And pleace post pictures of the layouts of the board.

I hope we'll see on the next gpn...

**Comment by LeoDJ** [comment]
More details for the breakout board can be found here: https://github.com/Jan--Henrik/hoverboard-breakout

**Comment by LeoDJ** [comment]
Is that what you were looking for? If yes, this issue can be closed.
