### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by eduards-kazakovs** [NiklasFauth/hoverboard-firmware-hack#29]
How does the timeout setting works? It doesn't seem to have any effect, If I don't send any commands, wheels just keep spinning at last speed.
Another thing I noticed - if motor control board is off and there is any input on uart2, it turns on.
Would be useful to have predefined on and off commands, but now it's bit scarry that it could come on any time, so I keep battery disconnected, when not using.

Thanks!!

**Comment by HITMAnsOFT** [comment]
I guess in your case the UART backpowers the MCU, causing it to turn the power latch on.  That would not cause a problem if the device connected to the UART is also powered by the motor control board. The current code enables the power latch (OFF_PIN in the code) unconditionally on startup. I think it might make sense to check the SWITCH_PIN state in the firmware before turning on the OFF_PIN.
