### ISSUE TITLE
Mainboard blew up

### ISSUE THREAD

**Issue by walterinho** [NiklasFauth/hoverboard-firmware-hack#32]
Hi there,

I did flash your code to my board successfully, but it blew up once I connected it.

![image](https://user-images.githubusercontent.com/11248857/42283333-04592a18-7fa1-11e8-952d-7375dedec3c9.png)

I don't know what was the problem, do you think I could replace those components?

**Comment by rene-dev** [comment]
you probably flashed unsupported hardware. post a pic of the rest of the board.

**Comment by walterinho** [comment]
This is the mainboard.

![image](https://user-images.githubusercontent.com/11248857/42283761-5ad4430e-7fa2-11e8-9adb-18b0c02e644e.png)

I do have another board (see below), but the st-link tool says there's no target connected:

![image](https://user-images.githubusercontent.com/11248857/42283880-b846b148-7fa2-11e8-98d3-7ce7cbe5c5ae.png)

Is there any other way in which you could please help me with some technical advice? it would only be a few minutes

**Comment by walterinho** [comment]
@rene-dev , How can I know if the hardware is supported?

I have this new mainboard, and I don't want to screw it up again.

![image](https://user-images.githubusercontent.com/11248857/42526985-4becab66-846f-11e8-872e-c793d03ee216.png)

**Comment by LeoDJ** [comment]
The best way to test it is to use a different power supply than the battery, that is current limited. Something like a lab bench power supply or if you feel adventurous and skilled enough the supplied hoverboard charger. But I highly recommend a lab bench power supply.
If the firmware on the mainboard tries to pull too much current, it will be limited by the supply instead of blowing components up with the high current from the battery.

**Comment by HITMAnsOFT** [comment]
Is that the buzzer control transistor? It shouldn't be fatal to the operation of the board. You can still try to run it with a current-limited power supply.

**Comment by johnsokol** [comment]
I have the tools to fix boards at the hackerdojo.

**Comment by walterinho** [comment]
Thank you very much for your help guys, please bear with me, I'm a noob at some topics in Electronics.

@LeoDJ, thanks! I followed your instructions with the new board and it works perfectly, I tested it with a maximum of 1.5A. Now my problem is that I need to use the hoverboard's battery, do you think that after doing these test it is safe to use it to the original battery with this board? or what options could I have?

@HITMAnsOFT yes, it is the buzzer control transistor and I thought the same but it doesn't work at all, I tried to test what is going on by connecting the oscilloscope to each motor phase and GND (I don't know if this is correct haha) and I realized that one of the phases of each motor doesn't change it's width (duty cycle) when I send a different speed and steer command. Is there a better way of checking what is wrong?

@johnsokol thanks for your help, the problem is that I live in London, =(, but I really appreciate that you are interested in helping me, maybe you have any advice about how to check what is wrong with the board.

**Comment by btsimonh** [comment]
@walterinho I have the same YST board, and all is working well.

**Comment by SafeMantella** [comment]
> The best way to test it is to use a different power supply than the battery, that is current limited. Something like a lab bench power supply or if you feel adventurous and skilled enough the supplied hoverboard charger. But I highly recommend a lab bench power supply.
> If the firmware on the mainboard tries to pull too much current, it will be limited by the supply instead of blowing components up with the high current from the battery.

What's the ideal voltage and current to test the board? I tried 36V 2.2A and nothing happened
