### ISSUE TITLE
Use of mainboard photo with connectors on YT video.

### ISSUE THREAD

**Issue by rokrodic** [NiklasFauth/hoverboard-firmware-hack#38]
Hi **Niklas**.
I make videos for youtube and would like to know if I can use your image on the main page (https://raw.githubusercontent.com/NiklasFauth/hoverboard-firmware-hack/master/pinout.png) in one (or more) of my videos? It is a video of making a hoverbike from hoverboard with your source code and my little contribution in Pull requests (hand throttle on ADC). I plan to use the photo, if you allow, and a link to your github page.
My channel: https://www.youtube.com/channel/UCIOIhhPirDJH8LB0azJmd8w
And where are you from? Germany, Austria, Swiss?
So, can I use it?
Rok

**Comment by Jan--Henrik** [comment]
Hi, the photos can be used according to the license.
