### ISSUE TITLE
wrong direction of stlink pins

### ISSUE THREAD

**Issue by hexxter** [NiklasFauth/hoverboard-firmware-hack#40]
Hi,
i have changed SWDIO and SWCLK and i see smoke. After if have changed this and programmed my pcb always after push the power button it beebs always in 0,5sec pulses.

Have anyone an idear what part form my pcb is dead?

It only beebs if i flash a firmware with nunchuck enable. Without nun it is not beebing ;)

BR Hexxter

**Comment by LeoDJ** [comment]
Reversing the clock and data lines of the programmer should not produce a hardware error. Are you sure you didn't reverse anything else?

**Comment by hexxter** [comment]
hi,
i'm not sure but i saw smoke and pull out the power cord. but after changing this pins in the right direktion. i can flash the pcb. and ich can control the motor via UART. But when i enable the Nunchuck then the pcb beebs always after switch it on.

BR Hexxter

**Comment by Jan--Henrik** [comment]
@hexxter did you disable UART while enabling I2C?

**Comment by hexxter** [comment]
i commt this out //#define DEBUG_SERIAL_USART3

**Comment by hexxter** [comment]
i have used the PCB with a 3v3 regulator but i think the pcb has an bug i see 10V on the nunchuck power pins. I have downloaded the new version from the PCB (the regulator was turned 90 °) and ordered a new pcb. i hobe ma nunchuck is not dead after this...

**Comment by Jan--Henrik** [comment]
Then you had an old version of the PCB. Probably the mainboard and/or the nunchuck is broken. Use a lab power supply for testing, but do not brake, as it is not regenerative.
