### ISSUE TITLE
The board wouldn't completely turn off

### ISSUE THREAD

**Issue by mbudris** [NiklasFauth/hoverboard-firmware-hack#41]
The board with default git code would not turn off. After the power button is pressed the motor is stopped, but the LED remains. From this point the board does not respond to anything. Needs power recycling.

The issue seemed to go away after I changed DELAY_IN_MAIN_LOOP to 5 in config.h:9
(even the comment indicates that the default value is 5, but git code has the value of 2).

**Comment by Jan--Henrik** [comment]
Thanks, fixed it :)
