### ISSUE TITLE
New style board; poweroff not working

### ISSUE THREAD

**Issue by btsimonh** [NiklasFauth/hoverboard-firmware-hack#44]
Hi All, 
I'm applying this to a YST-6.5"-10"-PCBA-10 board.

The original firmware loads, as does a version I built with platform.io.

However, it only works after a full power off.  A button-press power off stops the motors, and then after a period starts to issue short bleeps (no power down sequence bleep as the code hints at).

Anyone else had this kind of issue?

s

**Comment by p-h-a-i-l** [comment]
can confirm, when a motor is spinning, the power button shuts down the motor. Afterwards the board seems stuck until power cycling. Haven't noticed any beeps after pressing.
Shutdown works as expected when motors are stopped.

**Comment by goosst** [comment]
can confirm the issue, however I haven't spend time debugging the issue

**Comment by p-h-a-i-l** [comment]
I was testing with binaries created with make and without attached stlink.
