### ISSUE TITLE
[FeatureRequest] PID position control

### ISSUE THREAD

**Issue by EmerickH** [NiklasFauth/hoverboard-firmware-hack#53]
Hello,
Is it possible to implement PID in the motor controller to obtain more accurate speed and position control instead of speed?
I can help you on some parts but I don't know how to do, especially for the position.

Thank you

**Comment by btsimonh** [comment]
I've got a branch here https://github.com/btsimonh/hoverboard-firmware-hack/tree/withflashcalibration which includes reading the absolute hall sensor position.  I intend to enhance it to give absolute speed and position, and finish off my serial protocol for robust control.
Separating out the hall position should be quite easy, it's all in one file apart from a single change in Setup.c.  Getting speed should be a matter of reading a timer in the hall interrupt, and so knowing how long the hall segment took to progress.

**Comment by btsimonh** [comment]
now enhanced with speed.  Just need to rework the motor drive.  The hallinterrupt.h/c should be pretty portable into any version, just needs a couple of extra bits in _it.c and setup.c.
