### ISSUE TITLE
Please make a firmware for stm32, which will communicate with the ROS via the rosserial , like in turtlebot3

### ISSUE THREAD

**Issue by amburkoff** [NiklasFauth/hoverboard-firmware-hack#55]
Please make a firmware for stm32, which will communicate with the ROS via the rosserial, like here in turtlebot3 [http://emanual.robotis.com/docs/en/platform/turtlebot3/opencr_setup/#opencr-setup](http://emanual.robotis.com/docs/en/platform/turtlebot3/opencr_setup/#opencr-setup) .
About rosserial and the protocol of communication between the openCR and the raspberry pi can be read here [http://community.robotsource.org/t/download-the-ros-robot-programming-book-for-free/51](http://community.robotsource.org/t/download-the-ros-robot-programming-book-for-free/51)
It is necessary that the data on the odom and imu arrive correctly.

**Comment by NiklasFauth** [comment]
Okay. That makes ~5000€, I can probably make it within two weeks.

Seriously, what do you expect how Github / OS software development works? If you want a new feature, fork the project, implement it and if you think it is worth sharing, make a pull request.
All necessary hardware initialization for your application is already there, you just need to add the ROS specific software. Take a look at the CONTROL_SERIAL_USART2 define.
