### ISSUE TITLE
What application do you need to use to flash the firmware?

### ISSUE THREAD

**Issue by GuillaumeH8** [NiklasFauth/hoverboard-firmware-hack#56]
I downloaded the zipfile, but I don't see any application once unzipped. What application is needed to run the firmware and finally to flashing it??

**Comment by LeoDJ** [comment]
This project is not a product. It is meant to be used by hobbyists, that want to tinker around and as such does not have a stand-alone flasher or an easy-to-use interface.

The flashing process is well documented in the project Readme.

If you are unfamiliar with microcontroller development, you're probably out of luck.

**Comment by GuillaumeH8** [comment]
Okay thanks I'll try that
