### ISSUE TITLE
Unresponsive after poweron

### ISSUE THREAD

**Issue by chrismalyon** [NiklasFauth/hoverboard-firmware-hack#61]
I have two hoverboard both of which flash without issue. When I connect the battery and press the power button the boards appear to power on successfully and play the power up tone. However they both then become unresponsive and the power button will not shut them down. I have to disconnect the battery to power them down. Does anyone have any ideas what this could be?

**Comment by m-farahmand** [comment]
Yes, I got this problem.
please follow in [https://github.com/NiklasFauth/hoverboard-firmware-hack/issues/30](url) this link may be some body can help us ;(
