### ISSUE TITLE
program sequence

### ISSUE THREAD

**Issue by macuwe** [NiklasFauth/hoverboard-firmware-hack#66]
Hi, im probably in the wrong location to post it, but dont know where else to post it. 
So could someone help me get in the right direction?
I try to programm the mainboard with an raspberrypi zero w and this tutorial https://learn.adafruit.com/programming-microcontrollers-using-openocd-on-raspberry-pi/compiling-openocd
but im not sure if i should see some Serial data from the hoverboard-mainboard by default or if i have to unlock it first.
And also im not sure how to unlock it. I got this message 
Open On-Chip Debugger 0.10.0+dev-00546-g1afec4f5 (2018-10-04-22:55)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
BCM2835 GPIO config: tck = 11, tms = 25, tdi = 10, tdo = 9
BCM2835 GPIO nums: swclk = 11, swdio = 25
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
adapter speed: 1000 kHz
adapter_nsrst_delay: 100
jtag_ntrst_delay: 100
none separate
cortex_m reset_config sysresetreq
Info : BCM2835 GPIO JTAG/SWD bitbang driver
Info : JTAG and SWD modes enabled
open: Permission denied

Also i used the command from the readme, but shouldnt the unlock command contain something to make ocd communicate via SWD?
Sorry for these question. But i would love to have a better understanding of it.
Hope anybody can help me :) THX

**Comment by NiklasFauth** [comment]
Looks like you're missing permission to access the GPIOs of the raspberry pi. Try to run it as root.
