### ISSUE TITLE
Data from hal

### ISSUE THREAD

**Issue by ivliev123** [NiklasFauth/hoverboard-firmware-hack#67]
How are you get data from encoders whels

**Comment by rene-dev** [comment]
https://github.com/NiklasFauth/hoverboard-firmware-hack/blob/master/Src/bldc.c#L186-L203

**Comment by ivliev123** [comment]
how i can send this data to uart?

**Comment by LeoDJ** [comment]
I am currently looking into adding that functionality, but it will take a few days up to a few weeks depending on motivation and time.

**Comment by Dintojoseph** [comment]
Anybody can make full video
