### ISSUE TITLE
How to poweron/off solved on 4 wheel drive. Hence power on/off 2 hoverboard

### ISSUE THREAD

**Issue by BorgStefan** [NiklasFauth/hoverboard-firmware-hack#86]
Hi.
I have managed to get my skateboard to work with 2 wheel drive. I have 4 electrical and want to do have 4 wheel drive. But how to solve power on/off 2 mainboard?
How was that solved in bobbycar project?
![A3BC3F5B-8290-4F3A-A5F8-8A147E1B4478](https://user-images.githubusercontent.com/48124398/55376591-5fb4cc00-5511-11e9-817c-2f18997b81d0.jpeg)
Big thx for your excellent work!

**Comment by larsmm** [comment]
Connect 1 button via Y-cable directly to n mainboards.

**Comment by BorgStefan** [comment]
Great Thx!
