### ISSUE TITLE
Restore hoverboard firmware

### ISSUE THREAD

**Issue by gaucho1978** [NiklasFauth/hoverboard-firmware-hack#89]
I understood it is Not possibile to backup original firmware due to memory  lock. After unlocking the Arm and playing with this modified firmware, could I later flash a firmware that allows me to use again the device as a hoverboard?

**Comment by sh-hilden** [comment]
You can try this firmware: https://github.com/bipropellant/hoverboard-firmware. It is a firmware to use the hoverboard as a hoverboard

**Comment by 123JRM** [comment]
Niklas has made the above mentioned fork available at https://pionierland.de/hoverhack/index.php if your interested you can compile a working .bin directly.

**Comment by FarhatullahKhanbuzdar** [comment]
dear sh-hilden

> You can try this firmware: https://github.com/bipropellant/hoverboard-firmware. It is a firmware to use the hoverboard as a hoverboard

i cant find downloadable file like hex file in this code to use hoverboard as hoverboard.

**Comment by weiminshen99** [comment]
I have saved the original Factory flash from both the Master and Slave board before I hacked these boards.

If anyone is still interested, I believe these saved *.bin files can be flashed back to the boards and make them become the original hoverboard again.

**Comment by Candas1** [comment]
> I have saved the original Factory flash from both the Master and Slave board before I hacked these boards.
> 
> If anyone is still interested, I believe these saved *.bin files can be flashed back to the boards and make them become the original hoverboard again.

If you are talking about splitboards, this[https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x](this)  repository is currently active, you could share it there.

But there are many different board types so it's important to identify what type you have.
