### ISSUE TITLE
How to connect the button And i2c Lcd screen?

### ISSUE THREAD

**Issue by rojrung** [NiklasFauth/hoverboard-firmware-hack#91]
I successfully got my hoverboard control by ADC from joysticks
But now I want to build a Go kart with acceleration foot paddle
As I see in config.h it mentions on “button” for speed up the Bobby car
But I don’t know which wire are use for button on right sensor
I need this button to reverse my gokart

And for the wheelchair I want to see speed and battery indicator
So how to connect i2c lcd to right sensor cable

Thank you for all of you for this beautiful work

**Comment by verial** [comment]
failed too

**Comment by benjaf** [comment]
The i2c LCD code doesn't seem to work, so that is probably a part of the problem. If anyone has a good idea on how to fix it, that would be great!

**Comment by verial** [comment]
if you help me, I'll do it.

**Comment by verial** [comment]
https://www.youtube.com/watch?v=myu9lDYsH0E&feature=youtu.be
