### ISSUE TITLE
error during compilation

### ISSUE THREAD

**Issue by franck24300** [NiklasFauth/hoverboard-firmware-hack#99]
Hello
I do not know anything about programming but I would like to use this program. After modifying the config.h with Visual Studio Code to use the RC PPM command and compile by typing the make command in an Ubuntu terminal window, I get a hover.hex and hover.bin file, but when I flash in the motherboard, I can not rotate the wheels with the radio control and a PPM receiver. There is an error during compilation, maybe it's because of that? What is the cause of this error?

Src/stm32f1xx_it.c:224:5: warning: implicit declaration of function 'PPM_ISR_Callback'; did you mean 'PPM_SysTick_Callback'? [-Wimplicit-function-declaration]
     PPM_ISR_Callback();
     ^~~~~~~~~~~~~~~~
     PPM_SysTick_Callback

![compilation](https://user-images.githubusercontent.com/51533755/59160376-807f3c00-8ad5-11e9-86fd-48b6f57253af.jpg)

**Comment by larsmm** [comment]
There are warnings only. This is normal... Try CONTROL_MOTOR_TEST first.

**Comment by franck24300** [comment]
Yes CONTROL_MOTOR_TEST work. But not CONTROL_PPM
The difference when I compile that's it : PPM_Systick_Callback

**Comment by Candas1** [comment]
What type of receiver do you have? Have you tried changing to 8 channels in config. H?

**Comment by franck24300** [comment]
Yes it's good, I changed to 8 channels in the config.h and it works.
